### ISSUE TITLE
Searchable country input in profile settings

### ISSUE THREAD

**Issue by Alhakem** [Alhakem/coretabs-academy#392]
#Current Situation:
User has to scroll all way down until he find his country in a long list.

#Suggestion: 
Implementing autocomplete component such as  v-autocomplete instead of the select input.

Any ideas about this @LouayH

**Comment by LouayH** [comment]
We have a problem with v-autocomplete, v-textarea and other Vuetify's new components since they aren't supported in current used version, and the new version will break our website design.

I spent some hours previously working on it but didn't get it, maybe I'll give it another try when I have some time.

**Comment by Alhakem** [comment]
Aha, I see.

Okay great, I'll also try to come up with something about it and I'll let you know.

@LouayH

**Comment by Alhakem** [comment]
@LouayH 

I ended up working with a custom component, I pushed the updates please check if we are good to go with it.

**Comment by LouayH** [comment]
Good Try @Alhakem
